/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChinaMap3D: typeof import('./components/ChinaMap3D.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./components/Header.vue')['default']
    HeaderMap: typeof import('./components/HeaderMap.vue')['default']
    HeaderMap2: typeof import('./components/HeaderMap2.vue')['default']
    LoginButton: typeof import('./components/LoginButton.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    Photo: typeof import('./components/photo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHub: typeof import('./components/SearchHub.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TreeDetail3D: typeof import('./components/TreeDetail3D.vue')['default']
    Vedioe: typeof import('./components/vedioe.vue')['default']
  }
}
